### PR TITLE
fix: prevent external calls from being skipped

### LINKED ISSUE #67: External lib suddenly stopped working
I may be missing something, but apparently, in libvslI had

```
#include "extern_library.h"


struct return_value foo(char *arg) {
        (void)arg;
	return (struct return_value){
                .ptr = "Foo",
                .free = false,
   	};
}


struct extern_function *expose_library() {

        static struct extern_function lib[] = {
		{ "foo", foo }, {}
        };
        return lib;
}
```

and it worked. Then (out of nothing?) it's not working anymore.

```
./vinumc --with libvsl.so
[foo]
```

outputs nothing. Help needed.

### PR DESCRIPTION
**Pull request by JeanJPNM**
By ensuring calls to external functions always have an ARGS node, we can prevent them from being skipped during evaluation.
Fixes #67.

### CODE REVIEW

**Review by monacofj — APPROVED** [review]
Works fine

File: subprojects/vinumc/tests/library_test.c [hunk 1]
```diff
@@ -29,6 +29,15 @@ void test_empty_nested_call(struct vunit_test_ctx *ctx) {
...
+
+	vunit_run_vinumc_ok(ctx, "[parenthesize]", &out, "--with",
+			    "subprojects/vinumc/tests/libtestlib.so", NULL);
+
+	VUNIT_ASSERT_STREQ(ctx, out, "()");
+}
+
 VUNIT_TEST_SUITE("suite", { "Test extern library call", test_call },
 		 { "Test extern library call inside call", test_nested_call },
 		 { "Test nested empty library calls", test_empty_nested_call }, {}, )
```
Comment (JeanJPNM) [inline subprojects/vinumc/tests/library_test.c:43]: bruh, I forgot to add the new test to the test suite
