### PR TITLE
vinumc: reuse args rule to define a program's children

### LINKED ISSUE #48: Document must have a root block
How to reproduce:

Create a vinfile with

```[a: Hello]
x[a]
```

and compile it. It gives me

```
ERROR]:syntax error
```

### PR DESCRIPTION
**Pull request by JeanJPNM**
Fixes #48

### CODE REVIEW

File: subprojects/vinumc/tests/text_as_program_child.c [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+	char *out = NULL;
+
+	vunit_run_vinumc_ok(ctx, "$*", &out, NULL);
+
+	VUNIT_ASSERT_STREQ(ctx, out, "");
+}
+
+VUNIT_TEST_SUITE("suite", { "Simple text", test_simple_text },
+		 { "Mixed text and blocks", test_mixed_text_and_blocks },
+		 { "Ref all args should me empty", test_ref_all_args_is_empty }, {}, )
```
Comment (Grillo-0) [inline subprojects/vinumc/tests/text_as_program_child.c]: s/me/be

**Review by Grillo-0 — CHANGES_REQUESTED** [review]
Just the minnor spelling error and it's done

**Review by Grillo-0 — APPROVED** [review]
